apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: foos.example.com
spec:
    group: example.com
    version: v1
    scope: Namespaced
    names:
        plural: foos
        singular: foo
        kind: Foo
        shortNames:
            - foo
